name: Run Notion Invoice Automation

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:       # Allows manual triggering of the workflow

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Restore processed_pages.json
        uses: actions/cache@v3
        with:
          path: processed_pages.json
          key: processed-pages-cache-${{ github.run_id }}

      - name: Install Dependencies
        run: |
          pip install -r invoice_automation/requirements.txt

      - name: Run Invoice Automation Script
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        run: |
          python invoice_automation/invoice_automation.py

      - name: Save processed_pages.json
        uses: actions/cache@v3
        with:
          path: processed_pages.json
          key: processed-pages-cache-${{ github.run_id }}
