name: Run Notion Invoice Automation

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install -r invoice_automation/requirements.txt

      - name: Run Invoice Automation Script
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        run: python invoice_automation/invoice_automation.py

      - name: Debug Processed Pages
        run: cat processed_pages.json

      - name: Commit processed_pages.json
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add processed_pages.json
          git commit -m "Update processed_pages.json after run" || echo "No changes to commit"
          git push origin main
